# Site settings
title: Iran University of Science and Technology
course_name: Introduction to Wireless Networks
course_description: هدف از اين درس اين است که دانشجويان درک مناسبي از معماري شبکههاي بي سيم پيدا نموده و نيز با نحوه
عملکرد اين شبکهها آشنا شوند. در همين راستا علاوه بر مفاهيم پايه تئوري، دانشجويان بايستي عملا با اين
شبکهها و تکنولوژي هاي متعدد مربوطه آشنا شوند. علاوه بر اين دانشجويان اين درس با انجام پروژه فرصت
يادگيري عميق يکي از مباح مرتبط با درس را خواهند داشت.
course_semester: "Fall 2019"
description: |
    Instructor: Zhila Sadati

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://roozbehghazavi.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://roozbehghazavi.github.io/course_template/syllabus/
githubdir: 

# Author/user information
email: instructor-first-name@iust.ac.ir
twitter_username: broken_twitter 
github_username:  broken_github
authorurl: "http://borken-url.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
