# Site settings
title: Iran University of Science and Technology
course_name: Introduction to Wireless Networks
course_description: " Wireless networking is one of the fastest growing segments of the computer industry. Every electronic device seems capable of wireless connections these days: computers, handhelds, cell phones, and even digital cameras are all capable of transmitting without a tether. To many people, those wireless connections are nothing short of technical wizardry. This course will remove the mystery and give you a thorough understanding of this fascinating and lucrative technology. "
course_semester: "Fall 2019"
description: |
    Instructor: Abolfazl Dianat

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://roozbehghazavi.github.io/course_template" # the base hostname & protocol for your site
syllabus: "http://roozbehghazavi.github.io/course_template/syllabus/"
githubdir: 

# Author/user information
email: a.diyanat@ut.ac.ir
twitter_username:  
github_username:  
authorurl: "http://qa.parsilatex.com/user/%D8%A7%D8%A8%D9%88%D8%A7%D9%84%D9%81%D8%B6%D9%84+%D8%AF%DB%8C%D8%A7%D9%86%D8%AA"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
